#ifndef __ERRNO_H__
#define __ERRNO_H__

enum errno_t : int
{
  ERRNO_NOERROR        = 0,
  ERRNO_PERM           = -1,
  ERRNO_NOENT          = -2,
  ERRNO_SRCH           = -3,
  ERRNO_INTR           = -4,
  ERRNO_IO             = -5,
  ERRNO_NXIO           = -6,
  ERRNO_2BIG           = -7,
  ERRNO_NOEXEC         = -8,
  ERRNO_BADF           = -9,
  ERRNO_CHILD          = -10,
  ERRNO_AGAIN          = -11,
  ERRNO_NOMEM          = -12,
  ERRNO_ACCES          = -13,
  ERRNO_FAULT          = -14,
  ERRNO_NOTBLK         = -15,
  ERRNO_BUSY           = -16,
  ERRNO_EXIST          = -17,
  ERRNO_XDEV           = -18,
  ERRNO_NODEV          = -19,
  ERRNO_NOTDIR         = -20,
  ERRNO_ISDIR          = -21,
  ERRNO_INVAL          = -22,
  ERRNO_NFILE          = -23,
  ERRNO_MFILE          = -24,
  ERRNO_NOTTY          = -25,
  ERRNO_TXTBSY         = -26,
  ERRNO_FBIG           = -27,
  ERRNO_NOSPC          = -28,
  ERRNO_SPIPE          = -29,
  ERRNO_ROFS           = -30,
  ERRNO_MLINK          = -31,
  ERRNO_PIPE           = -32,
  ERRNO_DOM            = -33,
  ERRNO_RANGE          = -34,
  ERRNO_DEADLK         = -35,
  ERRNO_NAMETOOLONG    = -36,
  ERRNO_NOLCK          = -37,
  ERRNO_NOSYS          = -38,
  ERRNO_NOTEMPTY       = -39,
  ERRNO_LOOP           = -40,
  ERRNO_WOULDBLOCK     = ERRNO_AGAIN,
  ERRNO_NOMSG          = -42,
  ERRNO_IDRM           = -43,
  ERRNO_CHRNG          = -44,
  ERRNO_L2NSYNC        = -45,
  ERRNO_L3HLT          = -46,
  ERRNO_L3RST          = -47,
  ERRNO_LNRNG          = -48,
  ERRNO_UNATCH         = -49,
  ERRNO_NOCSI          = -50,
  ERRNO_L2HLT          = -51,
  ERRNO_BADE           = -52,
  ERRNO_BADR           = -53,
  ERRNO_XFULL          = -54,
  ERRNO_NOANO          = -55,
  ERRNO_BADRQC         = -56,
  ERRNO_BADSLT         = -57,
  ERRNO_DEADLOCK       = ERRNO_DEADLK,
  ERRNO_BFONT          = -59,
  ERRNO_NOSTR          = -60,
  ERRNO_NODATA         = -61,
  ERRNO_TIME           = -62,
  ERRNO_NOSR           = -63,
  ERRNO_NONET          = -64,
  ERRNO_NOPKG          = -65,
  ERRNO_REMOTE         = -66,
  ERRNO_NOLINK         = -67,
  ERRNO_ADV            = -68,
  ERRNO_SRMNT          = -69,
  ERRNO_COMM           = -70,
  ERRNO_PROTO          = -71,
  ERRNO_MULTIHOP       = -72,
  ERRNO_DOTDOT         = -73,
  ERRNO_BADMSG         = -74,
  ERRNO_OVERFLOW       = -75,
  ERRNO_NOTUNIQ        = -76,
  ERRNO_BADFD          = -77,
  ERRNO_REMCHG         = -78,
  ERRNO_LIBACC         = -79,
  ERRNO_LIBBAD         = -80,
  ERRNO_LIBSCN         = -81,
  ERRNO_LIBMAX         = -82,
  ERRNO_LIBEXEC        = -83,
  ERRNO_ILSEQ          = -84,
  ERRNO_RESTART        = -85,
  ERRNO_STRPIPE        = -86,
  ERRNO_USERS          = -87,
  ERRNO_NOTSOCK        = -88,
  ERRNO_DESTADDRREQ    = -89,
  ERRNO_MSGSIZE        = -90,
  ERRNO_PROTOTYPE      = -91,
  ERRNO_NOPROTOOPT     = -92,
  ERRNO_PROTONOSUPPORT = -93,
  ERRNO_SOCKTNOSUPPORT = -94,
  ERRNO_OPNOTSUPP      = -95,
  ERRNO_PFNOSUPPORT    = -96,
  ERRNO_AFNOSUPPORT    = -97,
  ERRNO_ADDRINUSE      = -98,
  ERRNO_ADDRNOTAVAIL   = -99,
  ERRNO_NETDOWN        = -100,
  ERRNO_NETUNREACH     = -101,
  ERRNO_NETRESET       = -102,
  ERRNO_CONNABORTED    = -103,
  ERRNO_CONNRESET      = -104,
  ERRNO_NOBUFS         = -105,
  ERRNO_ISCONN         = -106,
  ERRNO_NOTCONN        = -107,
  ERRNO_SHUTDOWN       = -108,
  ERRNO_TOOMANYREFS    = -109,
  ERRNO_TIMEDOUT       = -110,
  ERRNO_CONNREFUSED    = -111,
  ERRNO_HOSTDOWN       = -112,
  ERRNO_HOSTUNREACH    = -113,
  ERRNO_ALREADY        = -114,
  ERRNO_INPROGRESS     = -115,
  ERRNO_STALE          = -116,
  ERRNO_UCLEAN         = -117,
  ERRNO_NOTNAM         = -118,
  ERRNO_NAVAIL         = -119,
  ERRNO_ISNAM          = -120,
  ERRNO_REMOTEIO       = -121,
  ERRNO_DQUOT          = -122,
  ERRNO_NOMEDIUM       = -123,
  ERRNO_MEDIUMTYPE     = -124,
  ERRNO_CANCELED       = -125,
  ERRNO_NOKEY          = -126,
  ERRNO_KEYEXPIRED     = -127,
  ERRNO_KEYREVOKED     = -128,
  ERRNO_KEYREJECTED    = -129,
  ERRNO_OWNERDEAD      = -130,
  ERRNO_NOTRECOVERABLE = -131,
  ERRNO_RFKILL         = -132,
};

template<typename errno_type>
errno_type throw_errno(errno_type err) throw(errno_type)
{
  if(err < 0)
    throw(err);
  return err;
}

#endif
